### ISSUE TITLE
Switching between levels sometimes skips a level

### ISSUE THREAD

**Issue by bhatnathan** [Alexander-Hjelm/laser-game-ag19#29]
I get this bug when I start on level 1, and complete it, then level 2 is skipped. After this Level 1 is skipped every time, but level 2 is present. I'm not sure if this always happens or not, but it happens for me every time I tried it.

**Comment by bhatnathan** [comment]
This could possibly due to there being multiple calls to change the level and that occuring before we switch level. A possible solution is to have a transition or have a system of pressing a button to proceed to the next level.

**Comment by Alexander-Hjelm** [comment]
Most likely fixed by PQ #45. Must be tested on the pixelsense before closing.
