### ISSUE TITLE
Strange behavior after adding models

### ISSUE THREAD

**Issue by bhatnathan** [Alexander-Hjelm/laser-game-ag19#34]
It seems that after adding models right before the Hello World Demo, the scales of some of the game objects became messed up, which we believe affected the colliders and their sizes. To solve this issue go through each level and adjust values accordingly and make sure to apply the scaling to the prefabs in the projects.

**Comment by bhatnathan** [comment]
Things that need extra careful checking:
Mirrors
Black holes
Prisms
Targets

**Comment by Alexander-Hjelm** [comment]
Working on mirror collision on the branch mirror-collision-fix
