### ISSUE TITLE
Black hole causing multiple sparkling effects

### ISSUE THREAD

**Issue by bhatnathan** [Alexander-Hjelm/laser-game-ag19#35]
This happened when testing on the pixelsense. On level 4, the one with the black hole, multiple sparkling effects (that occur when the laser bounces against a object) appeared in places they were not supposed to. I am also not sure if this bug still happens for the current version of master, but needs to be checked on the pixelsense.

**Comment by Alexander-Hjelm** [comment]
No way to produce locally. Test the latest build on the pixelsense and see if the bug still presists.

**Comment by kaszim** [comment]
Fixed by #48 #45

**Comment by kaszim** [comment]
NVM, might be build issues. Try building from Windows.
