### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by bhatnathan** [Alexander-Hjelm/laser-game-ag19#37]
Go through all code and make sure it is clean, makes sense, and is commented properly. Quick check you don't have to be too careful!

**Comment by bhatnathan** [comment]
ObjectManager.cs and TUIOInput.cs need comments (too many is better than too few).

Kasim, maybe you can take care of those two files? Use the code-cleanup branch

**Comment by Alexander-Hjelm** [comment]
Merge this. If more documentation and cleanup is needed, open a new branch.

**Comment by bhatnathan** [comment]
Fixed in Pull request #63
