### ISSUE TITLE
Placeable Area for Laser Phycons

### ISSUE THREAD

**Issue by bhatnathan** [Alexander-Hjelm/laser-game-ag19#40]
There should be an area that is clearly marked (possibly with text) that this is where you can place a laser phycon. 

One should only be able to spawn one laser in each area.

The color of the laser spawned should be defined by the area.

The area should be easy to rescale (but the shape can be set, such as either a rectangle or circle)

**Comment by Alexander-Hjelm** [comment]
Assigned myself to make the graphical component of the zone
