### ISSUE TITLE
Rotational resolution on the Surface is low

### ISSUE THREAD

**Issue by Alexander-Hjelm** [Alexander-Hjelm/laser-game-ag19#41]
When rotating a phycon on the surface, the low resolution will make it problematic when the user tries to align the laser, and can't quite get the correct angle.

Suggestions for fixes:
  - Snap the reflection angle to fixed increments (degrees: 22.5, 45, 67.5...)
  - Provide some guidance for the laser. Correct the angle to hit the nearest object if it is close enough

**Comment by bhatnathan** [comment]
Something that might be cool is to slerp the angle between snaps (or even when we don't have artificial snaps). It could create a cool effect, make it easier to complete levels, and as long as the slerp happens fast enough it won't reduce responsiveness.
