### ISSUE TITLE
Lasers sometimes goes through switchable doors

### ISSUE THREAD

**Issue by kaszim** [Alexander-Hjelm/laser-game-ag19#96]
Seems to happen on a certain angle. Making the walls wider might solve the problem. @bhatnathan @Alexander-Hjelm

**Comment by Alexander-Hjelm** [comment]
Collision checks use interpolation in unity, so just making the box wider should not do anything. Can you post a picture that shows how to replicate this? @kaszim

**Comment by bhatnathan** [comment]
Ah I figured it out, this isn't an actual bug in any code, I just accidentally resized the door objects when I changed the models! I'll go through the levels and change the sizes of the doors to ensure that the stages work. (You can recreate this by creating a laser and pointing it at the corners of the doors for example on level 5).
